#!/usr/bin/env python3
"""Last step: manifest.txt, README.md and MANIFEST.tsv of one language pack,
plus the pack-wide checks that keep the pack translator-authored.

Run after every other generator (build_all.py does). Writes, in
<pack> = <out>/languages/<lang>/:

  manifest.txt   language metadata read by the engine and the menu
                 (display_name, codepage, subtitle_language, authors, ...)
  README.md      the pack's own documentation: creators, source, what the
                 pack holds and what was left out, with every number
                 re-derived from the files on disk
  MANIFEST.tsv   path <TAB> bytes <TAB> sha256 of every file except itself
                 and README.md, sorted by path (the deploy script pins its hash)

and FAILS (exit 1) when the pack breaks a rule of the pack reduction
(lang3, 2026-09-22):
  * any file byte-identical to any file of the canonical game;
  * any overlay/ image whose pixels equal the game's image of that path;
  * any whole model (.mdl) or whole entity lump (.ent) in the pack.

Hand-maintained files are kept as they are and listed in MANIFEST.tsv:
strings/menu-strings.tsv (the project's own menu, not the game) and
LICENSE-NOTE.md.

Usage: python build_manifest.py --lang polish [--pack-version 1.2.0]
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import langpack_common as lc  # noqa: E402

PACK_VERSION = "1.2.0"
HAND_MAINTAINED = ("strings/menu-strings.tsv", "LICENSE-NOTE.md")


def files_under(root: Path) -> list[Path]:
    return sorted((p for p in root.rglob("*") if p.is_file()), key=lambda p: p.as_posix().lower()) if root.exists() else []


def check_rules(lang: str) -> list[str]:
    pack = lc.lang_pack_dir(lang)
    problems = []
    for f in files_under(pack):
        rel = f.relative_to(pack).as_posix()
        if rel in ("MANIFEST.tsv",):
            continue
        if f.suffix.lower() in (".mdl", ".ent"):
            problems.append(f"{rel}: whole models / entity lumps are not shipped")
        same = lc.game_identical(f.read_bytes())
        if same is not None:
            problems.append(f"{rel}: byte-identical to the game's {same.relative_to(lc.CANONICAL_ROOT)}")
    for f in files_under(lc.overlay_dir(lang)):
        rel = f.relative_to(lc.overlay_dir(lang)).as_posix()
        canon = lc.find_ci(lc.CANONICAL_ROOT / rel)
        if canon is not None and f.suffix.lower() == ".tga":
            if lc.decode_tga(f.read_bytes()) == lc.decode_tga(canon.read_bytes()):
                problems.append(f"overlay/{rel}: pixel-identical to the game's image")
    return problems


def dll_string_notes(tsv: Path):
    rows = list(csv.DictReader(open(tsv, encoding="utf-8", newline=""), delimiter="\t")) if tsv.exists() else []
    flagged = [r for r in rows if r.get("flagged")]
    return rows, flagged


def md_table(rows, header):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def write_readme(lang: str, cfg: lc.LanguageConfig, pack_version: str, totals: dict) -> Path:
    pack = lc.lang_pack_dir(lang)
    ex = lc.EXCLUDED_ART.get(lang, {})
    rows, flagged = dll_string_notes(lc.dll_strings_tsv_path(lang))
    models = files_under(lc.models_dir(lang))
    model_names = sorted({str(p.parent.relative_to(pack).as_posix()) for p in models}, key=str.lower)
    n = totals
    L = []
    L += [f"# Cry of Fear: Spolszczenie (Polish language pack)" if lang == "polish" else f"# {cfg.display_name} language pack", ""]
    L += [f"A native, engine-loadable {cfg.display_name} language pack for Cry of Fear: Enhanced (code page "
          f"{cfg.codepage_label}), version {pack_version}. It is generated by "
          "[`scripts/polish/build_all.py`](../../scripts/polish/README.md) from the canonical game and the fan "
          "translation, and holds **only what the translators authored**: translated text, the key/value "
          "pairs they changed in the maps, and the images and model textures they repainted. Nothing in it is "
          "byte-identical to the game, and it contains no whole game asset (no maps, no models, no entity lumps). "
          "The layout and the engine side are described in "
          "[`docs/design/language-pack-format.md`](../../docs/design/language-pack-format.md) and "
          "[`docs/cof-language-packs.md`](../../docs/cof-language-packs.md).", ""]
    if lang == "polish":
        L += ["## Creators", "",
              "- **Avioo** (Tłumaczenie, grafiki, testowanie)",
              "- **Mixdedemon** (Tłumaczenie)",
              "- **hexag0n** (Technikalia, testowanie)",
              "- **Izonka** (Testowanie)", "",
              "## Source and permission", "",
              "The translation is the fan mod **Cry of Fear: Spolszczenie**, published on the Steam Workshop: "
              "<https://steamcommunity.com/sharedfiles/filedetails/?id=3164091802>. It was incorporated into this "
              "repository with the Polish localisation team's explicit permission (green light received "
              "2026-09-22). The underlying game content belongs to Team Psykskallar; see "
              "[`LICENSE-NOTE.md`](LICENSE-NOTE.md).", ""]
    L += ["## Contents", ""]
    L += md_table([
        ("`manifest.txt`", 1, "display name, code page, client subtitle slot, version, authors"),
        ("`txt/`", n["txt"], "subtitles, hints, conclusions, phone messages and notes, in the game's own "
         f"`txtfiles/languages/<lang>/` and `notes/languages/<lang>/` layout, {cfg.codepage} bytes"),
        ("`inventoryitems/`", n["inv"], "item and weapon names and descriptions, mirroring "
         f"`cryoffear/inventoryitems/`, {cfg.codepage} bytes"),
        ("`maps/*.entpatch`", n["maps"], f"per-map entity patches: {n['entvalues']} translated key/value "
         "pairs, applied by the engine to the map's own entity string at load"),
        ("`textures/*.tga`", n["tex"], "repainted world signs and posters, one per texture name"),
        ("`models/<model>/<texture>.bmp`", n["models"], f"repainted textures embedded in {len(model_names)} "
         "studio models (phone screens, newspapers, book pages, signs), 8-bit BMP; the engine swaps them "
         "into the loaded model"),
        ("`overlay/`", n["overlay"], "translated interface images (menus, notes, item and weapon cards, "
         "maps, dialogs), same path as the game's"),
        ("`strings/dll-strings.tsv`", 1, f"English -> {cfg.display_name} table for the strings compiled "
         f"into client.dll / hl.dll ({len(rows)} rows)"),
        ("`strings/menu-strings.tsv`", 1, "this project's own menu (hand-maintained, see below)"),
        ("`LICENSE-NOTE.md`, `README.md`, `MANIFEST.tsv`", 3, "licence note, this file, file list with hashes"),
    ], ["Path", "Files", "What"])
    L += ["", f"Total: **{n['files']} files, {n['bytes']:,} bytes** (every file but `MANIFEST.tsv` and "
          f"`README.md` is listed in `MANIFEST.tsv` with its size and SHA-256).", ""]

    L += ["## What was left out, and why", "",
          "The fan mod ships as a full standalone install. The generators keep only the translators' own "
          "work and leave out:", "",
          "- **Anything byte-identical to the game** (every generator writes through a check against all "
          "files of the game; nine `inventoryitems/weapons/weapon_*.txt` of the source are untouched game "
          "files).",
          "- **Whole maps and whole entity lumps.** The maps differ only in entity text and embedded sign "
          "textures; the pack carries the changed key/value pairs (`maps/*.entpatch`) and the repainted "
          "textures (`textures/`). Four changed values are asset paths the mod's find-and-replace broke "
          "(`ambience/docks.wav` -> `ambience/Doki.wav` in `c_hamn2` and `c_lake`) and are kept as the game "
          "has them.",
          "- **Whole models.** All 23 models the mod replaces differ from the game only in embedded texture "
          "pixels and palettes (checked byte by byte); the pack carries the repainted textures.",
          "- **Images whose pixels equal the game's**, and three sign textures the mod copied unchanged "
          "from other maps.",
          "- **The mod's repainted bitmap fonts** (this project renders the pack's code page with Inter), "
          "**its DLLs and EXEs** (strings are substituted at draw time from `dll-strings.tsv`), and **its "
          "118 MB startup video**.",
          "- **Art changed for reasons other than translation** (review of 2026-09-22; listed so the "
          "translators can say whether any of it should ship):", ""]
    ov = sorted(ex.get("overlay", {}).items())
    mo = sorted(ex.get("model", {}).items())
    L += md_table([(f"`overlay/{k}`", v) for k, v in ov] + [(f"model texture `{k}`", v) for k, v in mo],
                  ["File", "Why it is left out"])
    L += ["", "Kept, but worth a look: `gfx/vgui/hansts1.tga` and `saxts1.tga` (timetable maps: the "
          "title is translated, and the translators' base image also has the poster the other timetables "
          "carry), the phone skins `tex1.bmp` of five phone models (the SMS text is translated, and a "
          "'Sony Ericsson' logo was added), `models/cutscene/mobileprop/fullbright_mess2.bmp` (the "
          "translated SMS, drawn on a whole phone image where the game's texture has only the screen), "
          "and `gfx/vgui/language_settings.tga` (the English flag tile became a Polish one).", ""]

    L += ["## DLL strings (`strings/dll-strings.tsv`)", "",
          f"{len(rows)} rows recovered from the mod's hex patches of client.dll and hl.dll; 16 pairs the mod's "
          "blanket find-and-replace corrupted (identifiers such as `ammo_buckshot`, C-runtime day names, one "
          "overrun string) are excluded by offset in `build_dll_strings_tsv.py`. Rows whose mod bytes were "
          "chosen for the old bitmap font rather than real Windows-1250 are replaced by the project's "
          "corrections in `scripts/polish/string_overrides_polish.tsv`."]
    if flagged:
        kept = [r for r in flagged if r["flagged"].lower().startswith("kept english")]
        fixed = [r for r in flagged if r not in kept]
        L += [""]
        if fixed:
            L += [f"{len(fixed)} rows were retranslated by the project (the `flagged` column says so): "
                  + ", ".join(f"`{r['english'].strip(chr(16))}`" for r in fixed) + "."]
        if kept:
            L += ["", f"{len(kept)} identifier-like rows are kept in English by decision: "
                  + ", ".join(f"`{r['english']}`" for r in kept) + "."]
    L += ["", "## Menu strings (`strings/menu-strings.tsv`), machine-drafted, please review", "",
          "This file translates **this project's own menu** (main menu, Options pages, Extras, Unlockables, "
          "Credits, Save/Load, pause and death pages, co-op pages, dialogs, tooltips, the Controls list). It "
          "is not from the fan translation, which never touched this menu. It was drafted by an AI worker of "
          "this project on 2026-09-22 and is waiting for review by a Polish speaker. Format: `english <TAB> "
          "translation <TAB> where`, UTF-8; check it with `scripts/polish/extract-menu-strings.ps1`. It is "
          "hand-maintained: the generators keep it as it is.", ""]
    L += ["## Client subtitle slot (`subtitle_language=" + str(cfg.subtitle_language) + "`)", "",
          "The Language option sets the client's own subtitle slot (`cof_subtitlelanguage`) to this value. "
          "`1` is the client's English slot: the engine serves this pack's `txt/` files over whatever slot "
          "the client asks for, so anything the pack does not translate falls back to English.", ""]
    L += ["## Regeneration", "",
          "From the repository root, with the canonical game at `K:\\LLM\\COF_Fix\\Cry of Fear` and the fan "
          "translation at the path in `scripts/polish/langpack_common.py` (both read-only):", "",
          "```",
          f"python scripts/polish/build_all.py --lang {lang} --out .",
          "```", "",
          f"This rewrites every generated part of `languages/{lang}/` in place and keeps "
          "`strings/menu-strings.tsv` and `LICENSE-NOTE.md`. The DLL string step also reads the string "
          "tables of the binary analysis (`stage1/polish-mod-analysis-20260922/binaries/data/`). The result "
          "is byte-identical to the committed pack (checked 2026-09-22, `stage1/lang3-20260922`).", ""]
    out = pack / "README.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    return out


def write_pack_manifest_tsv(lang: str) -> Path:
    pack = lc.lang_pack_dir(lang)
    out_path = pack / "MANIFEST.tsv"
    rows = []
    for f in files_under(pack):
        rel = f.relative_to(pack).as_posix()
        if rel in ("MANIFEST.tsv", "README.md"):
            continue
        rows.append((rel, f.stat().st_size, lc.sha256_file(f)))
    rows.sort(key=lambda r: r[0])
    with open(out_path, "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, delimiter="\t", lineterminator="\n")
        w.writerow(["path", "bytes", "sha256"])
        for row in rows:
            w.writerow(row)
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lang", required=True, choices=sorted(lc.LANGUAGES))
    ap.add_argument("--pack-version", default=PACK_VERSION)
    args = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="backslashreplace")
    except Exception:
        pass

    cfg = lc.get_language(args.lang)
    pack = lc.lang_pack_dir(args.lang)
    for legacy in ("pack-README.md",):
        (pack / legacy).unlink(missing_ok=True)
    for h in HAND_MAINTAINED:
        if not (pack / h).is_file():
            print(f"WARNING: hand-maintained {h} is missing from {pack} (copy it in before building)")

    print(f"wrote {lc.write_manifest_txt(args.lang, pack_version=args.pack_version)}")

    problems = check_rules(args.lang)

    entvalues = 0
    for f in files_under(lc.maps_dir(args.lang)):
        entvalues += sum(1 for line in f.read_bytes().splitlines()
                         if line.startswith(b'"') and not line.startswith(b'"@'))
    # MANIFEST.tsv first (README counts include it), then README, then MANIFEST.tsv again is not
    # needed: README.md is not listed in MANIFEST.tsv.
    tsv = write_pack_manifest_tsv(args.lang)
    listed = sum(1 for _ in open(tsv, encoding="utf-8")) - 1
    all_files = files_under(pack)
    totals = dict(
        txt=len(files_under(lc.txt_dir(args.lang))),
        inv=len(files_under(lc.inventoryitems_dir(args.lang))),
        maps=len(files_under(lc.maps_dir(args.lang))),
        entvalues=entvalues,
        tex=len(files_under(lc.textures_dir(args.lang))),
        models=len(files_under(lc.models_dir(args.lang))),
        overlay=len(files_under(lc.overlay_dir(args.lang))),
        files=len([f for f in all_files if f.name != "README.md"]) + 1,
        bytes=0,
    )
    readme = write_readme(args.lang, cfg, args.pack_version, totals)
    # the README states the total including itself: two passes settle its own size
    for _ in range(3):
        all_files = files_under(pack)
        total = sum(f.stat().st_size for f in all_files)
        if totals["bytes"] == total and totals["files"] == len(all_files):
            break
        totals["bytes"], totals["files"] = total, len(all_files)
        readme = write_readme(args.lang, cfg, args.pack_version, totals)
    print(f"wrote {readme}")
    print(f"wrote {tsv} ({listed} files listed)")
    print(f"pack: {totals['files']} files, {totals['bytes']:,} bytes "
          f"(txt {totals['txt']}, inventoryitems {totals['inv']}, entpatch {totals['maps']} / {entvalues} values, "
          f"textures {totals['tex']}, model textures {totals['models']}, overlay {totals['overlay']})")
    if problems:
        print("PACK RULE VIOLATIONS:")
        for p in problems:
            print(f"  {p}")
        return 1
    print("pack rules: OK (nothing identical to the game, no whole models or entity lumps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
