[CmdletBinding()]
param(
    [string]$SourceRoot = (Join-Path $PSScriptRoot '..'),
    [string]$OutputDirectory = (Join-Path (Join-Path $PSScriptRoot '..') 'build-launcher'),
    [string]$VcVarsPath = ''
)

$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$SourceRoot = [IO.Path]::GetFullPath($SourceRoot)
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$source = Join-Path $SourceRoot 'launcher\cof_launch.cpp'
$resource = Join-Path $SourceRoot 'launcher\cof_launch.rc'
$icon = Join-Path $projectRoot 'assets\branding\coffix.ico'
$versionFile = Join-Path $projectRoot 'VERSION'

$projectPrefix = $projectRoot.TrimEnd('\') + '\'
if (-not $SourceRoot.StartsWith($projectPrefix, [StringComparison]::OrdinalIgnoreCase) -and
    $SourceRoot -ne $projectRoot) {
    throw "SourceRoot must be inside this project workspace: $projectRoot"
}
if (-not $OutputDirectory.StartsWith($projectPrefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw "OutputDirectory must be inside this project workspace: $projectRoot"
}

if ([string]::IsNullOrWhiteSpace($VcVarsPath)) {
    $vswhere = Get-Command vswhere.exe -ErrorAction SilentlyContinue
    if ($vswhere) {
        $installationPath = (& $vswhere.Source -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath | Select-Object -First 1)
        if ($installationPath) {
            $VcVarsPath = Join-Path $installationPath 'VC\Auxiliary\Build\vcvarsall.bat'
        }
    }
}
if ([string]::IsNullOrWhiteSpace($VcVarsPath) -and $env:VSINSTALLDIR) {
    $VcVarsPath = Join-Path $env:VSINSTALLDIR 'VC\Auxiliary\Build\vcvarsall.bat'
}
if ([string]::IsNullOrWhiteSpace($VcVarsPath)) {
    throw 'Visual Studio vcvarsall.bat was not found; pass -VcVarsPath explicitly.'
}
$vcvars = [IO.Path]::GetFullPath($VcVarsPath)

if (-not (Test-Path -LiteralPath $vcvars)) {
    throw "VS2022 x86 toolchain not found: $vcvars"
}
if (-not (Test-Path -LiteralPath $source)) {
    throw "Launcher source not found: $source"
}
if (-not (Test-Path -LiteralPath $resource)) {
    throw "Launcher resource not found: $resource"
}
if (-not (Test-Path -LiteralPath $icon)) {
    throw "Branding icon not found: $icon"
}

New-Item -ItemType Directory -Force -Path $OutputDirectory | Out-Null

# The version resource (ProductName / FileDescription "Cry of Fear Enhanced",
# the name Windows and recorders show) takes its version from VERSION line 1,
# e.g. "0.4.0-test1": FILEVERSION 0,4,0,0 and the string as it is.
if (-not (Test-Path -LiteralPath $versionFile)) { throw "VERSION not found: $versionFile" }
$versionLine = ([IO.File]::ReadAllLines($versionFile) | Select-Object -First 1).Trim()
if ($versionLine -notmatch '^(\d+)\.(\d+)(?:\.(\d+))?') { throw "VERSION line 1 does not start with a version number: $versionLine" }
$fileVersion = '{0},{1},{2},0' -f [int]$Matches[1], [int]$Matches[2], $(if ($Matches[3]) { [int]$Matches[3] } else { 0 })
if ($versionLine -match '["\\]') { throw "VERSION line 1 may not contain quotes or backslashes: $versionLine" }
$versionHeader = @(
    '// generated by scripts\build-cof-launcher.ps1 from VERSION; do not edit',
    "#define COF_LAUNCH_FILEVERSION $fileVersion",
    "#define COF_LAUNCH_VERSION_STR `"$versionLine`""
) -join "`r`n"
[IO.File]::WriteAllText((Join-Path $OutputDirectory 'cof_launch_version.h'), $versionHeader + "`r`n", (New-Object Text.ASCIIEncoding))
Write-Host "launcher version resource: $versionLine ($fileVersion)"
$obj = Join-Path $OutputDirectory 'cof_launch.obj'
$res = Join-Path $OutputDirectory 'cof_launch.res'
$exe = Join-Path $OutputDirectory 'CoFLaunchApp.exe'
$sourceArg = $source.Replace('"', '""')
$resourceArg = $resource.Replace('"', '""')
$iconDirArg = (Split-Path -Parent $icon).Replace('"', '""')
$outDirArg = $OutputDirectory.TrimEnd('\').Replace('"', '""')
$resArg = $res.Replace('"', '""')
$exeArg = $exe.Replace('"', '""')
$command = "call `"$vcvars`" x86 && rc /nologo /i `"$iconDirArg`" /i `"$outDirArg`" /fo `"$resArg`" `"$resourceArg`" && cl /nologo /W4 /EHsc /O2 /MT /DWIN32_LEAN_AND_MEAN `"$sourceArg`" `"$resArg`" /link user32.lib /LARGEADDRESSAWARE /SUBSYSTEM:CONSOLE /OUT:`"$exeArg`" /PDB:`"$($exe -replace '\.exe$','.pdb')`""
Push-Location $OutputDirectory
try {
    & cmd.exe /d /s /c $command
    if ($LASTEXITCODE -ne 0) { throw "cl failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

Get-FileHash -LiteralPath $exe -Algorithm SHA256
