#Requires -Version 5.1
<#
.SYNOPSIS
  Generate engine/cof_version.h for the "cofenhanced" build stamp.

.DESCRIPTION
  The engine draws a second version line under Xash3D's own, and appends the
  same string to the styled console's title band:

      cofenhanced 0.3 (m3, f105554)

  The three parts come from this repository, not from the engine checkout:

      COFE_VERSION    line 1 of cof-fix\VERSION
      COFE_MILESTONE  line 2 of cof-fix\VERSION
      COFE_COMMIT     git rev-parse --short HEAD in cof-fix, plus "+" when the
                      tracked tree is dirty

  The engine source includes the header only when it exists (__has_include) and
  falls back to "dev" values otherwise, so a plain apply of
  patches/cof-cofenhanced-version.patch compiles with no generated file. Run
  this before a build to stamp the real values.

.PARAMETER SourceRoot
  The Xash3D FWGS checkout to write into. Must be inside the workspace.

.PARAMETER Project
  The cof-fix repository that carries VERSION and the git history.
#>
[CmdletBinding()]
param(
	[string]$Project    = 'K:\LLM\COF_Fix\cof-fix',
	[string]$SourceRoot = 'K:\LLM\COF_Fix\cof-fix\xash3d-fwgs-4857b389e6ba32ddaa68582aedcbc950c138f46a',
	[switch]$Remove
)
$ErrorActionPreference = 'Stop'

$workspace = 'K:\LLM\COF_Fix'
foreach ($p in @($Project, $SourceRoot)) {
	$full = [System.IO.Path]::GetFullPath($p)
	if (-not $full.StartsWith($workspace, [StringComparison]::OrdinalIgnoreCase)) {
		throw "Refusing to touch '$full': outside $workspace"
	}
	if (-not (Test-Path -LiteralPath $full -PathType Container)) { throw "Not a directory: $full" }
}

$header = Join-Path $SourceRoot 'engine\cof_version.h'

if ($Remove) {
	if (Test-Path -LiteralPath $header) { Remove-Item -LiteralPath $header -Force; Write-Host "removed $header" }
	else { Write-Host "nothing to remove at $header" }
	return
}

$versionFile = Join-Path $Project 'VERSION'
if (-not (Test-Path -LiteralPath $versionFile)) { throw "Missing $versionFile" }
$lines = @(Get-Content -LiteralPath $versionFile | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' })
if ($lines.Count -lt 2) { throw "$versionFile must hold the version on line 1 and the milestone on line 2" }
$version   = $lines[0]
$milestone = $lines[1]

Push-Location $Project
try {
	$commit = (& git rev-parse --short HEAD 2>$null)
	if ($LASTEXITCODE -ne 0 -or -not $commit) { $commit = 'nogit' }
	else {
		$commit = $commit.Trim()
		$dirty = (& git status --porcelain --untracked-files=no 2>$null)
		if ($LASTEXITCODE -eq 0 -and $dirty) { $commit = "$commit+" }
	}
} finally { Pop-Location }

foreach ($v in @($version, $milestone, $commit)) {
	if ($v -match '[""\\\r\n]') { throw "Refusing to emit '$v': it would break the C string literal" }
}

$text = @"
/*
cof_version.h - generated by cof-fix\scripts\write-cof-version.ps1. Do not edit.

The "cofenhanced" build stamp drawn under the engine version line and in the
styled console's title band. Regenerate before a build; the engine falls back
to "dev" values when this file is absent.
*/
#ifndef COF_VERSION_H
#define COF_VERSION_H

#define COFE_VERSION   "$version"
#define COFE_MILESTONE "$milestone"
#define COFE_COMMIT    "$commit"

#endif // COF_VERSION_H
"@

New-Item -ItemType Directory -Force -Path (Split-Path $header) | Out-Null
# LF, no BOM: the engine tree is LF and this file is generated, never committed
[System.IO.File]::WriteAllText($header, ($text -replace "`r`n", "`n"), (New-Object System.Text.UTF8Encoding($false)))

Write-Host "wrote $header"
Write-Host "  cofenhanced $version ($milestone, $commit)"
